stages:
  - install
  - test
  - quality

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

test:
  stage: test
  script:
    - npx cypress run
  artifacts:
    paths:
      - cypress/videos/
      - cypress/screenshots/
    expire_in: 1 week
  dependencies:
    - install


qodana:
  image:
    name: jetbrains/qodana-js:2024.2
    entrypoint: [""]
  cache:
    - key: qodana-2024.2-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2024.2-$CI_DEFAULT_BRANCH-
        - qodana-2024.2-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $QODANA_TOKEN
    QODANA_ENDPOINT: "https://qodana.cloud"
  script:
    - qodana --cache-dir=$CI_PROJECT_DIR/.qodana/cache
